// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// kll_new
SEXP kll_new(SEXP k_);
RcppExport SEXP _kll_kll_new(SEXP k_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type k_(k_SEXP);
    rcpp_result_gen = Rcpp::wrap(kll_new(k_));
    return rcpp_result_gen;
END_RCPP
}
// kll_update
SEXP kll_update(SEXP kll_, NumericVector values);
RcppExport SEXP _kll_kll_update(SEXP kll_SEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type kll_(kll_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(kll_update(kll_, values));
    return rcpp_result_gen;
END_RCPP
}
// kll_cdf_impl
SEXP kll_cdf_impl(SEXP kll_);
RcppExport SEXP _kll_kll_cdf_impl(SEXP kll_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type kll_(kll_SEXP);
    rcpp_result_gen = Rcpp::wrap(kll_cdf_impl(kll_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kll_kll_new", (DL_FUNC) &_kll_kll_new, 1},
    {"_kll_kll_update", (DL_FUNC) &_kll_kll_update, 2},
    {"_kll_kll_cdf_impl", (DL_FUNC) &_kll_kll_cdf_impl, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_kll(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
