# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kll_new <- function(k_) {
    .Call('_kll_kll_new', PACKAGE = 'kll', k_)
}

kll_update <- function(kll_, values) {
    .Call('_kll_kll_update', PACKAGE = 'kll', kll_, values)
}

kll_cdf_impl <- function(kll_) {
    .Call('_kll_kll_cdf_impl', PACKAGE = 'kll', kll_)
}

